### PR TITLE
arch-handbook translate

### PR DESCRIPTION
**Pull request by ghost**
Some arch-handbook transaltion.

### CODE REVIEW

**Comment by dbaio** [comment]
Thank you @ccc1924 
Could you help on this @yzgyyang ?

**Comment by ghost** [comment]
Yes.We translate handbook on http://translate.fugbr.org

**Comment by yzgyyang** [comment]
Thanks @ccc1924! I will take a look @dbaio.

**Comment by ghost** [comment]
already import to http://translate.fugbr.org.Close this pull request

**Pull request closed without merging**
